version: "2"
services:
  voctoweb:
    build: .
    command: dumb-init bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/voctoweb
      - "./docker/database.yml:/voctoweb/config/database.yml"
      - "./docker/settings.yml:/voctoweb/config/settings.yml"
    ports:
      - "3000:3000"
    environment:
      - ELASTICSEARCH_URL=elasticsearch
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - sidekiq
      - postgres
      - elasticsearch
      - redis
      - ssh-server
  sidekiq:
    build: .
    command: dumb-init bundle exec sidekiq
    volumes:
      - ".:/voctoweb"
      - "./docker/database.yml:/voctoweb/config/database.yml"
      - "./docker/settings.yml:/voctoweb/config/settings.yml"
    environment:
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:alpine
    volumes:
      - "./docker/db:/var/lib/postgresql/data:rw"
  elasticsearch:
    image: elasticsearch:5-alpine
    ports:
      - "9200:9200"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  ssh-server:
    image: panubo/sshd
    volumes:
      - ".:/voctoweb"
      - "./docker/ssh:/root/.ssh"
    ports:
      - "2202:22"
  nginx:
    image: nginx
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/content:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
    depends_on:
      - voctoweb
