defaults: &defaults
  frontend_proto: http
  frontend_host: localhost.c3voc.de
  cdn_url: http://cdn.localhost.c3voc.de
  static_url: http://static.localhost.c3voc.de/media
  cors_url: http://cdn.localhost.c3voc.de
  folders:
    recordings_webroot: ''
    images_webroot: ""
    tmp_dir: "/tmp"
  header:
    google: 2ozQIr-cQ-sJzGeJT_iTkS147fs3c5R3I1i6Dk_YLwA
  feeds:
    base_url: "http://localhost.c3voc.de/"
    channel_title: Chaos Computer Club
    channel_subtitle: A wide variety of video material distributed by the CCC. All content
      is taken from cdn.localhost.c3voc.de and media.ccc.de
    channel_description: Der Chaos Computer Club ist die größte europäische Hackervereinigung,
      und seit über 25 Jahren Vermittler im Spannungsfeld technischer und sozialer Entwicklungen.
    channel_summary: A wide variety of video material distributed by the Chaos Computer
      Club.
    channel_owner: CCC media team
    channel_keywords: CCC Congress Hacking Security Netzpolitik

development:
  <<: *defaults
test:
  <<: *defaults
  static_url: http://static.localhost.c3voc.de/media
  folders:
    recordings_webroot: ''
    images_webroot: ''
    tmp_dir: '/tmp'

production:
  <<: *defaults
